package gov.redhawk.ExtendedCF;

/**
* gov/redhawk/ExtendedCF/ResourceDescHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/efe/redhawk/git/gov.redhawk.core/plugins/gov.redhawk.sandbox/idl/ossie/CF/sandbox.idl
* Monday, May 20, 2013 5:01:28 PM EDT
*/

public final class ResourceDescHolder implements org.omg.CORBA.portable.Streamable
{
  public gov.redhawk.ExtendedCF.ResourceDesc value = null;

  public ResourceDescHolder ()
  {
  }

  public ResourceDescHolder (gov.redhawk.ExtendedCF.ResourceDesc initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = gov.redhawk.ExtendedCF.ResourceDescHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    gov.redhawk.ExtendedCF.ResourceDescHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return gov.redhawk.ExtendedCF.ResourceDescHelper.type ();
  }

}
