package gov.redhawk.ExtendedCF;


/**
* gov/redhawk/ExtendedCF/ResourceDesc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/efe/redhawk/git/gov.redhawk.core/plugins/gov.redhawk.sandbox/idl/ossie/CF/sandbox.idl
* Monday, May 20, 2013 5:01:28 PM EDT
*/

public final class ResourceDesc implements org.omg.CORBA.portable.IDLEntity
{

  /**
               * The Object this resource describes
               */
  public CF.Resource resource = null;

  /**
               * The id of this resource's profile
               */
  public String profile = null;

  public ResourceDesc ()
  {
  } // ctor

  public ResourceDesc (CF.Resource _resource, String _profile)
  {
    resource = _resource;
    profile = _profile;
  } // ctor

} // class ResourceDesc
