package gov.redhawk.ExtendedCF;


/**
* gov/redhawk/ExtendedCF/ResourceDescHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/efe/redhawk/git/gov.redhawk.core/plugins/gov.redhawk.sandbox/idl/ossie/CF/sandbox.idl
* Monday, May 20, 2013 5:01:28 PM EDT
*/

abstract public class ResourceDescHelper
{
  private static String  _id = "IDL:redhawk.gov/ExtendedCF/ResourceDesc:1.0";

  public static void insert (org.omg.CORBA.Any a, gov.redhawk.ExtendedCF.ResourceDesc that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static gov.redhawk.ExtendedCF.ResourceDesc extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = CF.ResourceHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "resource",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "profile",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (gov.redhawk.ExtendedCF.ResourceDescHelper.id (), "ResourceDesc", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static gov.redhawk.ExtendedCF.ResourceDesc read (org.omg.CORBA.portable.InputStream istream)
  {
    gov.redhawk.ExtendedCF.ResourceDesc value = new gov.redhawk.ExtendedCF.ResourceDesc ();
    value.resource = CF.ResourceHelper.read (istream);
    value.profile = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, gov.redhawk.ExtendedCF.ResourceDesc value)
  {
    CF.ResourceHelper.write (ostream, value.resource);
    ostream.write_string (value.profile);
  }

}
