package gov.redhawk.ExtendedCF;


/**
* gov/redhawk/ExtendedCF/SandboxOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/efe/redhawk/git/gov.redhawk.core/plugins/gov.redhawk.sandbox/idl/ossie/CF/sandbox.idl
* Monday, May 20, 2013 5:01:28 PM EDT
*/


/**
         * Interface to the Sandbox
         */
public interface SandboxOperations 
{

  /**
               * Resolves to a NamingContext that elements should be bound to in order to appear in this container
               */
  org.omg.CosNaming.NamingContext namingContext ();

  /**
               * Resolves to a CF::DeviceManager that CF::Device elements should register with to appear in the container
               */
  CF.DeviceManager deviceManager ();

  /**
               * Current SCA profiles (as defined in appendix D) that are available
               */
  String[] availableProfiles ();

  /**
               * File Manager for the Sandbox
               */
  CF.FileManager fileManager ();

  /**
               * Resources currently registered with the system.
               */
  gov.redhawk.ExtendedCF.ResourceDesc[] registeredResources ();

  /**
               * Get the resource factory of the given type
               * @param identifier an profile id as found in availableProfiles
               */
  CF.ResourceFactory getResourceFactory (String identifier);

  /**
               * Get the resource factory of the given profile
               * @param identifier an profile id as found in availableProfiles
               */
  CF.ResourceFactory getResourceFactoryByProfile (String profile);

  /**
               * Tell the sandbox to refresh the state of the object
               * @param obj The object to refresh
               * @param dpth The depth to which to refresh this object
               */
  void refresh (org.omg.CORBA.Object obj, gov.redhawk.ExtendedCF.SandboxPackage.Depth dpth);
} // interface SandboxOperations
