package gov.redhawk.ExtendedCF;

/**
* gov/redhawk/ExtendedCF/SandboxHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/efe/redhawk/git/gov.redhawk.core/plugins/gov.redhawk.sandbox/idl/ossie/CF/sandbox.idl
* Monday, May 20, 2013 5:01:28 PM EDT
*/


/**
         * Interface to the Sandbox
         */
public final class SandboxHolder implements org.omg.CORBA.portable.Streamable
{
  public gov.redhawk.ExtendedCF.Sandbox value = null;

  public SandboxHolder ()
  {
  }

  public SandboxHolder (gov.redhawk.ExtendedCF.Sandbox initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = gov.redhawk.ExtendedCF.SandboxHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    gov.redhawk.ExtendedCF.SandboxHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return gov.redhawk.ExtendedCF.SandboxHelper.type ();
  }

}
