package gov.redhawk.ExtendedCF;


/**
* gov/redhawk/ExtendedCF/Sandbox.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/efe/redhawk/git/gov.redhawk.core/plugins/gov.redhawk.sandbox/idl/ossie/CF/sandbox.idl
* Monday, May 20, 2013 5:01:28 PM EDT
*/


/**
         * Interface to the Sandbox
         */
public interface Sandbox extends SandboxOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{

  /**
          	 * ID for DataType that signifies the launch mode to create a resource in
          	 */
  public static final String LAUNCH_TYPE = "__launchType";

  /**
  			 * Value of launch data type signifying to launch resource in Debug Launch Mode
  			 */
  public static final String LAUNCH_TYPE_DEBUG = "debug";

  /**
  			 * Value of launch data type signifying to launch resource in (standard) run Launch Mode
  			 */
  public static final String LAUNCH_TYPE_RUN = "run";
} // interface Sandbox
