package gov.redhawk.ExtendedCF;


/**
* gov/redhawk/ExtendedCF/SandboxHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/efe/redhawk/git/gov.redhawk.core/plugins/gov.redhawk.sandbox/idl/ossie/CF/sandbox.idl
* Monday, May 20, 2013 5:01:28 PM EDT
*/


/**
         * Interface to the Sandbox
         */
abstract public class SandboxHelper
{
  private static String  _id = "IDL:redhawk.gov/ExtendedCF/Sandbox:1.0";

  public static void insert (org.omg.CORBA.Any a, gov.redhawk.ExtendedCF.Sandbox that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static gov.redhawk.ExtendedCF.Sandbox extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (gov.redhawk.ExtendedCF.SandboxHelper.id (), "Sandbox");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static gov.redhawk.ExtendedCF.Sandbox read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SandboxStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, gov.redhawk.ExtendedCF.Sandbox value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static gov.redhawk.ExtendedCF.Sandbox narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof gov.redhawk.ExtendedCF.Sandbox)
      return (gov.redhawk.ExtendedCF.Sandbox)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      gov.redhawk.ExtendedCF._SandboxStub stub = new gov.redhawk.ExtendedCF._SandboxStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static gov.redhawk.ExtendedCF.Sandbox unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof gov.redhawk.ExtendedCF.Sandbox)
      return (gov.redhawk.ExtendedCF.Sandbox)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      gov.redhawk.ExtendedCF._SandboxStub stub = new gov.redhawk.ExtendedCF._SandboxStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
