package gov.redhawk.ExtendedCF.SandboxPackage;

/**
* gov/redhawk/ExtendedCF/SandboxPackage/DepthHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/efe/redhawk/git/gov.redhawk.core/plugins/gov.redhawk.sandbox/idl/ossie/CF/sandbox.idl
* Monday, May 20, 2013 5:01:28 PM EDT
*/


/**
             * Enumeration of depths types
             */
public final class DepthHolder implements org.omg.CORBA.portable.Streamable
{
  public gov.redhawk.ExtendedCF.SandboxPackage.Depth value = null;

  public DepthHolder ()
  {
  }

  public DepthHolder (gov.redhawk.ExtendedCF.SandboxPackage.Depth initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = gov.redhawk.ExtendedCF.SandboxPackage.DepthHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    gov.redhawk.ExtendedCF.SandboxPackage.DepthHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return gov.redhawk.ExtendedCF.SandboxPackage.DepthHelper.type ();
  }

}
