package gov.redhawk.ExtendedCF.SandboxPackage;


/**
* gov/redhawk/ExtendedCF/SandboxPackage/DepthHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/efe/redhawk/git/gov.redhawk.core/plugins/gov.redhawk.sandbox/idl/ossie/CF/sandbox.idl
* Monday, May 20, 2013 5:01:28 PM EDT
*/


/**
             * Enumeration of depths types
             */
abstract public class DepthHelper
{
  private static String  _id = "IDL:redhawk.gov/ExtendedCF/Sandbox/Depth:1.0";

  public static void insert (org.omg.CORBA.Any a, gov.redhawk.ExtendedCF.SandboxPackage.Depth that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static gov.redhawk.ExtendedCF.SandboxPackage.Depth extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (gov.redhawk.ExtendedCF.SandboxPackage.DepthHelper.id (), "Depth", new String[] { "FULL", "SELF"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static gov.redhawk.ExtendedCF.SandboxPackage.Depth read (org.omg.CORBA.portable.InputStream istream)
  {
    return gov.redhawk.ExtendedCF.SandboxPackage.Depth.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, gov.redhawk.ExtendedCF.SandboxPackage.Depth value)
  {
    ostream.write_long (value.value ());
  }

}
