package gov.redhawk.ExtendedCF.SandboxPackage;


/**
* gov/redhawk/ExtendedCF/SandboxPackage/Depth.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/efe/redhawk/git/gov.redhawk.core/plugins/gov.redhawk.sandbox/idl/ossie/CF/sandbox.idl
* Monday, May 20, 2013 5:01:28 PM EDT
*/


/**
             * Enumeration of depths types
             */
public class Depth implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static gov.redhawk.ExtendedCF.SandboxPackage.Depth[] __array = new gov.redhawk.ExtendedCF.SandboxPackage.Depth [__size];

  public static final int _FULL = 0;
  public static final gov.redhawk.ExtendedCF.SandboxPackage.Depth FULL = new gov.redhawk.ExtendedCF.SandboxPackage.Depth(_FULL);
  public static final int _SELF = 1;
  public static final gov.redhawk.ExtendedCF.SandboxPackage.Depth SELF = new gov.redhawk.ExtendedCF.SandboxPackage.Depth(_SELF);

  public int value ()
  {
    return __value;
  }

  public static gov.redhawk.ExtendedCF.SandboxPackage.Depth from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Depth (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Depth
