package gov.redhawk.ExtendedCF.SandboxPackage;


/**
* gov/redhawk/ExtendedCF/SandboxPackage/ProfileDescSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/efe/redhawk/git/gov.redhawk.core/plugins/gov.redhawk.sandbox/idl/ossie/CF/sandbox.idl
* Monday, May 20, 2013 5:01:28 PM EDT
*/

public final class ProfileDescSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ProfileDescSequenceHolder ()
  {
  }

  public ProfileDescSequenceHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = gov.redhawk.ExtendedCF.SandboxPackage.ProfileDescSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    gov.redhawk.ExtendedCF.SandboxPackage.ProfileDescSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return gov.redhawk.ExtendedCF.SandboxPackage.ProfileDescSequenceHelper.type ();
  }

}
